# Generated by Django 5.2.1 on 2025-05-22 20:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=64)),
                ('city', models.CharField(max_length=65)),
                ('street', models.CharField(max_length=128)),
                ('house_number', models.CharField(blank=True, max_length=16, null=True)),
                ('apartment_number', models.CharField(blank=True, max_length=16, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=19, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='addresses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'address',
            },
        ),
        migrations.CreateModel(
            name='Rent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=90)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('rooms_count', models.PositiveSmallIntegerField(default=0)),
                ('room_type', models.CharField(choices=[('SINGLE_ROOM', 'Одна комната (студия)'), ('ONE_BEDROOM', 'Одна комната с отдельной спальней'), ('TWO_BEDROOM', 'Две комнаты с общей ванной'), ('TWO_BEDROOM_ENSUITE', 'Две комнаты с отдельными ванными'), ('THREE_BEDROOM', 'Три комнаты'), ('SUITE', 'Сьют / Апартаменты'), ('SHARED_ROOM', 'Общая комната / койко-место'), ('PRIVATE_ROOM_IN_SHARED', 'Отдельная комната в общей квартире'), ('LOFT', 'Лофт / Мансарда'), ('STUDIO', 'Студия')], max_length=36)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rents', to='rent.address')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'rent',
            },
        ),
        migrations.AddConstraint(
            model_name='address',
            constraint=models.UniqueConstraint(fields=('country', 'city', 'street', 'apartment_number'), name='unique_address_with_apartment'),
        ),
    ]
