# Generated by Django 5.2.1 on 2025-05-23 10:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='rent',
            name='room_type',
            field=models.CharField(choices=[('SINGLE_ROOM', 'Одна комната (студия)'), ('ONE_BEDROOM', 'Одна комната с отдельной спальней'), ('TWO_BEDROOM', 'Две комнаты с общей ванной'), ('TWO_BEDROOM_ENSUITE', 'Две комнаты с отдельными ванными'), ('THREE_BEDROOM', 'Три комнаты'), ('SUITE', 'Сьют / Апартаменты'), ('SHARED_ROOM', 'Общая комната / койко-место'), ('PRIVATE_ROOM_IN_SHARED', 'Отдельная комната в общей квартире'), ('LOFT', 'Лофт / Мансарда'), ('STUDIO', 'Студия'), ('HAUS', 'Дом')], max_length=36),
        ),
        migrations.AddConstraint(
            model_name='rent',
            constraint=models.UniqueConstraint(fields=('title', 'description', 'address', 'is_deleted'), name='unique_listing_title_desc_address_not_deleted'),
        ),
    ]
