# Generated by Django 5.2.1 on 2025-05-26 08:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0002_alter_rent_room_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='rent',
            name='unique_listing_title_desc_address_not_deleted',
        ),
        migrations.AddConstraint(
            model_name='rent',
            constraint=models.UniqueConstraint(fields=('title', 'address', 'is_deleted'), name='unique_listing_title_desc_address_not_deleted'),
        ),
    ]
