# Generated by Django 5.2.1 on 2025-05-27 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0003_remove_rent_unique_listing_title_desc_address_not_deleted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rent',
            name='avg_rating',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='rent',
            name='cn_views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
