# Generated by Django 5.2.1 on 2025-05-27 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0004_rent_avg_rating_rent_cn_views'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='rent',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='rent',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
