# Generated by Django 5.2.1 on 2025-06-01 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0005_alter_address_options_alter_rent_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rent',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='rent',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='rent',
            name='price',
            field=models.DecimalField(db_index=True, decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='rent',
            name='title',
            field=models.CharField(db_index=True, max_length=90),
        ),
    ]
