# Generated by Django 5.2.1 on 2025-06-01 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0006_alter_rent_is_active_alter_rent_is_deleted_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rent',
            options={'ordering': ['-avg_rating']},
        ),
    ]
