# Generated by Django 5.2.1 on 2025-06-02 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0007_alter_rent_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rent',
            name='description',
            field=models.TextField(max_length=500),
        ),
    ]
