# Generated by Django 5.2.1 on 2025-05-23 19:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rent', '0002_alter_rent_room_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('PENDING', 'В ожидании'), ('CONFIRMED', 'Подтверждено'), ('CANCELLED', 'Отменено'), ('DECLINED', 'Отклонено')], default='PENDING', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lessee', models.ForeignKey(limit_choices_to={'role': 'LESSEE'}, on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL)),
                ('rent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='rent.rent')),
            ],
            options={
                'db_table': 'booking',
                'ordering': ['-created_at'],
                'constraints': [models.CheckConstraint(condition=models.Q(('end_date__gt', models.F('start_date'))), name='booking_valid_date_range'), models.UniqueConstraint(fields=('lessee', 'rent', 'start_date', 'end_date'), name='unique_booking_per_user_rent_period')],
            },
        ),
    ]
