# Generated by Django 5.2.1 on 2025-05-23 19:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
        ('rent', '0002_alter_rent_room_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='booking',
            name='unique_booking_per_user_rent_period',
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.UniqueConstraint(fields=('lessee', 'rent', 'start_date', 'end_date'), name='unique_booking_per_user_rent_period'),
        ),
    ]
