# Generated by Django 5.2.1 on 2025-06-01 18:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_booking_updated_at'),
        ('rent', '0006_alter_rent_is_active_alter_rent_is_deleted_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='end_date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='start_date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('PENDING', 'В ожидании'), ('CONFIRMED', 'Подтверждено'), ('CANCELLED', 'Отменено'), ('DECLINED', 'Отклонено')], db_index=True, default='PENDING', max_length=10),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['rent', 'start_date', 'end_date'], name='booking_date_check_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['status', 'start_date'], name='booking_status_date_idx'),
        ),
    ]
